### ISSUE TITLE
Missing partial redspot/_header Error deploying plugin on redmine 3.4.11

### ISSUE THREAD

**Issue by jcabannes** [synbioz/redspot-redmine-plugin#1]
Hello,

I installed the plugin on a redmine 3.4.11 running on Debian GNU/Linux 9 (stretch) virtual machine which has ruby 2.3.8p459 installed.

I get the following error when I try to access to my redmine :

App 11951 output: Started GET "/" for xxx.xxx.xxx.xxx at 2019-07-02 14:05:01 +0000
App 11951 output: Processing by WelcomeController#index as HTML
App 11951 output:   Current user: anonymous
App 11951 output:   Rendered welcome/index.html.erb within layouts/base (30.3ms)
App 11951 output: Missing template, responding with 404
App 11951 output:   Rendered common/error.html.erb within layouts/base (0.6ms)
App 11951 output: Completed 500 Internal Server Error in 353ms (ActiveRecord: 8.0ms)
App 11951 output: 
App 11951 output: ActionView::Template::Error (Missing partial redspot/_header with {:locale=>[:fr, :en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :rsb]}. Searched in:
App 11951 output:   * "/var/data/redmine/app/views"
App 11951 output: ):
App 11951 output:     121:  ` <div class="bgl"><div class="bgr">`
App 11951 output:     122:     Powered by <%= link_to Redmine::Info.app_name, Redmine::Info.url %> &copy; 2006-2019 Jean-Philippe Lang
App 11951 output:     123:   `</div></div>`
App 11951 output:     124: `</div>`
App 11951 output:     125: `</div>`
App 11951 output:     126: `</div>`
App 11951 output:     127: <%= call_hook :view_layouts_base_body_bottom %>
App 11951 output:   lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
App 11951 output:   lib/redmine/hook/view_listener.rb:57:in `map'
App 11951 output:   lib/redmine/hook/view_listener.rb:57:in `block in render_on'
App 11951 output:   lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
App 11951 output:   lib/redmine/hook.rb:61:in `each'
App 11951 output:   lib/redmine/hook.rb:61:in `block in call_hook'
App 11951 output:   lib/redmine/hook.rb:58:in `tap'
App 11951 output:   lib/redmine/hook.rb:58:in `call_hook'
App 11951 output:   lib/redmine/hook.rb:96:in `call_hook'
App 11951 output:   app/views/layouts/base.html.erb:124:in `_app_views_layouts_base_html_erb__3892903097762575707_47147271065460'
App 11951 output:   app/controllers/application_controller.rb:491:in `block (2 levels) in render_error'
App 11951 output:   app/controllers/application_controller.rb:489:in `render_error'
App 11951 output:   app/controllers/application_controller.rb:477:in `render_404'
App 11951 output:   app/controllers/application_controller.rb:501:in `missing_template'
App 11951 output: 
App 11951 output:

**Comment by victordarras** [comment]
Hi @jcabannes, It seems that Redmine is not searching in the correct directory. I'll try to reproduce your environment in the week and let you know if I find something.
thx for using (or tryin') Redspot :p
